name: smart_legal_assistant
description: "A unified Smart Legal Assistant Flutter project for Clients and Lawyers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.1.2
  cloud_firestore: ^5.0.2
  http: ^1.2.0
  intl: ^0.19.0
  signature: ^5.5.0
  file_picker: ^8.1.2
  flutter_local_notifications: ^17.0.0
  rxdart: ^0.27.7
  url_launcher: ^6.3.0
  cloudinary_public: ^0.23.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.11.0
  share_plus: ^7.2.1
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
