// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQP_4C2i-KvTJs7EeM_KyxShTP8NXTmqA',
    appId: '1:636284975962:web:6443c75163afe7c41c7945b70a', // Placeholder for Web
    messagingSenderId: '636284975962',
    projectId: 'smart-legal-assistant-app',
    authDomain: 'smart-legal-assistant-app.firebaseapp.com',
    storageBucket: 'smart-legal-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQP_4C2i-KvTJs7EeM_KyxShTP8NXTmqA',
    appId: '1:636284975962:android:afe7c41c7945b70ac75163',
    messagingSenderId: '636284975962',
    projectId: 'smart-legal-assistant-app',
    storageBucket: 'smart-legal-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQP_4C2i-KvTJs7EeM_KyxShTP8NXTmqA',
    appId: '1:636284975962:ios:afe7c41c7945b70ac75163', // Placeholder for iOS
    messagingSenderId: '636284975962',
    projectId: 'smart-legal-assistant-app',
    storageBucket: 'smart-legal-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
