// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQP_4C2i-KvTJs7EeM_KyxShTP8NXTmqA',
    appId: '1:636284975962:web:temporaryid', // Web App ID is different from Android
    messagingSenderId: '636284975962',
    projectId: 'smart-legal-assistant-app',
    authDomain: 'smart-legal-assistant-app.firebaseapp.com',
    storageBucket: 'smart-legal-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQP_4C2i-KvTJs7EeM_KyxShTP8NXTmqA',
    appId: '1:636284975962:android:afe7c41c7945b70ac75163',
    messagingSenderId: '636284975962',
    projectId: 'smart-legal-assistant-app',
    storageBucket: 'smart-legal-assistant-app.firebasestorage.app',
  );
}
